name: ChromiumDriver Build
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x, 16.x, 18.x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install latest npm
        run: npm install -g npm
      - name: Install dependencies
        uses: bahmutov/npm-install@1a235c31658a322a3b024444759650ee6345c26d # tag=v1
        with:
          useRollingCache: true
          install-command: npm ci --foreground-scripts
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Print Chrome version
        shell: bash
        run: |
          if ["$RUNNER_OS" == "macOS"]; then
            chromium --version
          else
            chrome --version
          fi
      - name: Start Display
        shell: bash
        run: |
          if ["$RUNNER_OS" == "Windows"]; then
            echo "Not starting display since on Windows"
          else
            DISPLAY=:99 sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          fi
      - name: Run smoke, unit & E2E tests
        run: DISPLAY=:99 npm run test:ci

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Install dependencies
        uses: bahmutov/npm-install@1a235c31658a322a3b024444759650ee6345c26d # tag=v1
        with:
          useRollingCache: true
          install-command: npm ci --foreground-scripts
      - name: ESLint
        run: npm run lint
      - name: Validate Renovate Config
        uses: rinchsan/renovate-config-validator@1ea1e8514f6a33fdd71c40b0a5fa3512b9e7b936 # tag=v0
        with:
          pattern: '{.renovaterc.json,renovate/default.json}'
